version: '3'

services:
  borg:
    build:
      context: .
      dockerfile: Dockerfile

    image: horaceworblehat/borg-server
    environment:
      # Specify you public ssh keys here. Separate keys by adding \n
      BORG_AUTHORIZED_KEYS: "<key_one>\n<key_two>"
    volumes:
      - backup:/home/borg/backups
      - server_keys:/var/lib/docker-borg
    ports:
      - "8022:22"

volumes:
  backup:
  server_keys:
