version: '3'

services:
  borg:
    image: ghcr.io/anotherstranger/borg-server:2.4.1

    environment:
      # Specify you public ssh keys here. You can also separate keys by adding \n
      BORG_AUTHORIZED_KEYS: |
        # comment
        key_one
        # another comment
        key_two
      # BORG_AUTHORIZED_KEYS: key_one\nkey_two
      BORG_SERVE_ADDITIONAL_ARGS: "--storage-quota 900G --append-only"
      BORG_UID: "1000"
      BORG_GID: "1000"
    volumes:
      - backup:/home/borg/backups
      - server_keys:/var/lib/docker-borg
      # - <path to authorized_keys file>:/home/borg/.ssh/authorized_keys <- Alternative to BORG_AUTHORIZED_KEYS
    ports:
      - "8022:22"

volumes:
  backup:
  server_keys:
