version: '3'

services:
  borg:
    build:
      context: .
      dockerfile: Dockerfile

    image: horaceworblehat/borg-server
    environment:
      # Specify you public ssh keys here. Separate keys by adding \n
      BORG_AUTHORIZED_KEYS: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM7/8kuSuApH3ABTZxrSgOhjVqByfosFw7BtIWTFgW6N andre@andre-work\nssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOvM7aEEYbgjlakMkJd6pziDGpz1BpN1uGpiEX4+gw2w buesgen@fh-aachen.de"
      BORG_SERVE_ADDITIONAL_ARGS: "--storage-quota 900G --append-only"
      BORG_UID: "1000"
      BORG_GID: "1000"
    volumes:
      - backup:/home/borg/backups
      - server_keys:/var/lib/docker-borg
    ports:
      - "8022:22"

volumes:
  backup:
  server_keys:
