name: 'Run Security Tests'
on:
  push:
    branches:
      - main
      - dev
  pull_request:
  schedule:
    - cron: '* * * * 0' # run weekly
permissions:
  contents: read
  actions: read
  checks: write
  security-events: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          scan-type: 'fs'
          format: 'sarif'
          output: 'trivy-results-fs.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4
        with:
          sarif_file: 'trivy-results-fs.sarif'
